### ISSUE TITLE
Swift?

### ISSUE THREAD

**Issue by nawar** [microsoftgraph/msgraph-sdk-objc#4]
Since this is a new project spinning off the older one, I'd recommend having the following:

- Include sample code in Swift.
- Integrate this as cocoa pod. 
- Include support for SPM.

**Comment by dadheech115** [comment]
@nawar Thanks for putting up the request.

- For Swift Samples -  we will soon be releasing the sample on the usage of this library. As of now, after integrating the library in your project, you can add a Bridging-Header to use this Obj-C library in Swift projects.
- CocoaPods - As of now the library is still in preview stage. So we decided to go with Carthage support only. Once we reach GA phase with this library, we will add the support to integrate it as CocoaPod.
- Support for SPM -  This library is written in Objective-C and SPM supports the distribution of Swift code only.
